version: 2
updates:
  - package-ecosystem: npm
    directory: /service
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - "@angular/*"
      testing:
        patterns:
          - "karma*"
          - "@types/jasmine"
          - "jasmine-core"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
